name: what-is-context

on:
 push:
   branches:
     - main
jobs:     
 build_flow:
    runs-on: [self-hosted, linux]
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
