name: Lint go code

on: 
 push: 
   branches:
     - main
     
     
jobs:
 lint:
  runs-on: ubuntu-14.04
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: 
        stable: 'false'
        go-version: '1.14.1'
    - name: lint
      run: |
        curl -sSfL https://github.com/golangci/golangci-lint/blob/bbc2f34dec3d3cb7e00f15b838acc2e5f052e253/install.sh
        sh -s  -- -b $(go eng GOPATH)/bin v1.26.0
        glangcli-lint run
        
