name: publish-image-docker

on:
 push:
   branches:
     - main
     
jobs:
  build-n-publish:
     runs-on: ubuntu-latest
     
     steps:
       - uses: actions/checkout@v2
       
       - uses: actions/setup-go@v2
         with: 
           stable: 'false'
           go-version: '1.14.1'
           
       - name: build go application
         run:  sh -S -- -b $(go env GOPATh)/bin v1.26.0 | go build ./http-server.go -o main
         
       - name: run http server
         run:  ./main
         
       - name: check curl status 
         run: curl -I http://localhost:3333
         

       - name: build-image
         run: docker build .  --tag work-flow-test:v1
        
         
         
         
       - name: pubkish-image
         uses: elgohr/Publish-Docker-Github-Action@master
         with: 
           name: djmule001/workflow-actions
           username: ${{ secrets.REPO_USERNAME }}
           password: ${{ secrets.REPO_password }}
