name: publish-image-docker

on:
 push:
   branches:
     - main
     
jobs:
  build-n-publish:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: build-image
         run: docker build .  --tag work-flow-test:v1
         
       - name: run-docker
         run: docker run -it work-flow-test:v1 -p 3333:3333 --name diksha-trial 
         
       - name: check http status 
         run:  curl http://localhost:3333 -I 
         
         
         
       - name: pubkish-image
         uses: elgohr/Publish-Docker-Github-Action@master
         with: 
           name: djmule001/workflow-actions
           username: ${{ secrets.REPO_USERNAME }}
           password: ${{ secrets.REPO_password }}
