name: publish-image-docker

on:
 push:
   branches:
     - main
     
jobs:
  build-n-publish:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: build-image
         run: docker build . --tag work-flow-test:$(date +%s)
         
       - name: pubkish-image
         uses: elgohr/Publish-Docker-Github-Action@master
         with: 
           name: djmule001/workflow-actions
           username: ${{ secrets.REPO_USERNAME }}
           password: ${{ secrets.REPO_password }}
